spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paperdata?serverTimezone=CTT&characterEncoding=UTF-8&interactiveClient=true&autoReconnect=true&useSSL=false
    username: root
    password: zcy1998917
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

server:
  port: 8088

mybatis:
  mapper-locations: classpath:daoImpl/*Mapper.xml
